// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCopyrightAttribute("Copyright ©2013-2018 ICT Baden GmbH")]
[assembly: AssemblyCompanyAttribute("ICT Baden GmbH")]
[assembly: AssemblyProductAttribute("X-Platform & Web Application Framework")]
[assembly: AssemblyVersionAttribute("3.0.7")]
[assembly: AssemblyFileVersionAttribute("3.0.7")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyCopyright = "Copyright ©2013-2018 ICT Baden GmbH";
        internal const System.String AssemblyCompany = "ICT Baden GmbH";
        internal const System.String AssemblyProduct = "X-Platform & Web Application Framework";
        internal const System.String AssemblyVersion = "3.0.7";
        internal const System.String AssemblyFileVersion = "3.0.7";
    }
}
