// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCopyrightAttribute("Copyright ©2013-2019 ICT Baden GmbH")]
[assembly: AssemblyCompanyAttribute("ICT Baden GmbH")]
[assembly: AssemblyProductAttribute("X-Platform and Web Application Framework")]
[assembly: AssemblyVersionAttribute("3.3.1")]
[assembly: AssemblyFileVersionAttribute("3.3.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyCopyright = "Copyright ©2013-2019 ICT Baden GmbH";
        internal const System.String AssemblyCompany = "ICT Baden GmbH";
        internal const System.String AssemblyProduct = "X-Platform and Web Application Framework";
        internal const System.String AssemblyVersion = "3.3.1";
        internal const System.String AssemblyFileVersion = "3.3.1";
    }
}
