// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCopyrightAttribute("Copyright ©2013-2018 ICT Baden GmbH")]
[assembly: AssemblyCompanyAttribute("ICT Baden GmbH")]
[assembly: AssemblyProductAttribute("Web Application Framework")]
[assembly: AssemblyVersionAttribute("3.0.2")]
[assembly: AssemblyFileVersionAttribute("3.0.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyCopyright = "Copyright ©2013-2018 ICT Baden GmbH";
        internal const System.String AssemblyCompany = "ICT Baden GmbH";
        internal const System.String AssemblyProduct = "Web Application Framework";
        internal const System.String AssemblyVersion = "3.0.2";
        internal const System.String AssemblyFileVersion = "3.0.2";
    }
}
